
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maryem 
 */
public class Pyramide_Form extends javax.swing.JFrame {

    /**
     * Creates new form Pyramide_Form
     */
    public Pyramide_Form() {
        initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Wrong  input Format exception (DocumentFilter)
        ((AbstractDocument) iText.getDocument()).setDocumentFilter(new FilterJframeText() );
         ((AbstractDocument) wText.getDocument()).setDocumentFilter(new FilterJframeText() );
         ((AbstractDocument) hText.getDocument()).setDocumentFilter(new FilterJframeText() );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        iText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        wText = new javax.swing.JTextField();
        RText = new javax.swing.JTextField();
        hText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setText("Pyramide Volume ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("berechnen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        iText.setBackground(new java.awt.Color(255, 255, 255));
        iText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        iText.setForeground(new java.awt.Color(51, 51, 51));
        iText.setBorder(null);
        getContentPane().add(iText, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 86, 80, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pyramide.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 67, -1, 201));

        wText.setBackground(new java.awt.Color(255, 255, 255));
        wText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        wText.setForeground(new java.awt.Color(51, 51, 51));
        wText.setBorder(null);
        wText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wTextActionPerformed(evt);
            }
        });
        getContentPane().add(wText, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 129, 80, -1));

        RText.setBackground(new java.awt.Color(255, 255, 255));
        RText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        RText.setForeground(new java.awt.Color(51, 51, 51));
        RText.setText("Result");
        RText.setBorder(null);
        getContentPane().add(RText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 120, -1));

        hText.setBackground(new java.awt.Color(255, 255, 255));
        hText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hText.setForeground(new java.awt.Color(51, 51, 51));
        hText.setBorder(null);
        hText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hTextActionPerformed(evt);
            }
        });
        getContentPane().add(hText, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 168, 80, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("I");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 88, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("w");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 131, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("h:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("berechnen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("berechnen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        double I = ParseDouble(iText.getText());
        double W = ParseDouble(wText.getText());
        double h = ParseDouble(hText.getText());
           // Calculate the Pyramide's Volume:
         Double Res = (h*I*W)/3;
        //Round the Result 2numbers after coma '.' 
       Res=Math.round(Res*100.0)/100.0;
         RText.setText(Res.toString());
    }
    
         
//Make Exception for Empty File
   double ParseDouble(String strNumber) {
   if (strNumber != null && strNumber.length() > 0) {
                

       try {
          return Double.parseDouble(strNumber);
       } catch(NumberFormatException e) {
        
          return -1;   
          
       }
   }
   else return 0;

    }//GEN-LAST:event_jButton1ActionPerformed

    private void hTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hTextActionPerformed

    private void wTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pyramide_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pyramide_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pyramide_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pyramide_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pyramide_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RText;
    private javax.swing.JTextField hText;
    private javax.swing.JTextField iText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField wText;
    // End of variables declaration//GEN-END:variables
}
