
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DocumentFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maryem
 */
public class Quader_Form extends javax.swing.JFrame {

    /**
     * Creates new form Quader_Form
     */
    public Quader_Form() {
        initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         
        //Wrong  input Format exception DocumentFilter
         ((AbstractDocument) aText.getDocument()).setDocumentFilter(new FilterJframeText() );
         ((AbstractDocument) bText.getDocument()).setDocumentFilter(new FilterJframeText() );
         ((AbstractDocument) hText.getDocument()).setDocumentFilter(new FilterJframeText() );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        aText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bText = new javax.swing.JTextField();
        RTest = new javax.swing.JTextField();
        hText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setText("Quader Volume ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        aText.setBackground(new java.awt.Color(255, 255, 255));
        aText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        aText.setForeground(new java.awt.Color(102, 102, 102));
        aText.setBorder(null);
        aText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        aText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTextActionPerformed(evt);
            }
        });
        jPanel1.add(aText, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 95, 80, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Quarder.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 212, 192));

        bText.setBackground(new java.awt.Color(255, 255, 255));
        bText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        bText.setForeground(new java.awt.Color(102, 102, 102));
        bText.setBorder(null);
        bText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        bText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTextActionPerformed(evt);
            }
        });
        jPanel1.add(bText, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 138, 80, -1));

        RTest.setBackground(new java.awt.Color(255, 255, 255));
        RTest.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        RTest.setForeground(new java.awt.Color(102, 102, 102));
        RTest.setText("result ");
        RTest.setBorder(null);
        RTest.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        RTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTestActionPerformed(evt);
            }
        });
        jPanel1.add(RTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 120, -1));

        hText.setBackground(new java.awt.Color(255, 255, 255));
        hText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        hText.setForeground(new java.awt.Color(102, 102, 102));
        hText.setBorder(null);
        hText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        hText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hTextActionPerformed(evt);
            }
        });
        jPanel1.add(hText, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 177, 80, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("a:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 97, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("b:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("h:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 179, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("berechnen");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 298, 100, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

// Calculate the Cube Volume:
        // Fomule : V = a · b · c oder V=a*a*a
       
                
        double a = ParseDouble(aText.getText());
        double b = ParseDouble(bText.getText());
        double h = ParseDouble(hText.getText());
        Double Res = (a*b*h);
        //Round the Result 2number after coma '.' 
        Res=Math.round(Res*100.0)/100.0;
         RTest.setText(Res.toString());
    }
    //Make Exception for Empty File
   double ParseDouble(String strNumber) {
   if (strNumber != null && strNumber.length() > 0) {
       try {
          return Double.parseDouble(strNumber);
       } catch(NumberFormatException e) {
           
          return -1;   
          
       }
   }
   else return 0;

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bTextActionPerformed

    private void hTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hTextActionPerformed

    private void RTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RTestActionPerformed

    private void aTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTextActionPerformed
/*
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quader_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Quader_Form().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RTest;
    private javax.swing.JTextField aText;
    private javax.swing.JTextField bText;
    private javax.swing.JTextField hText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
